CREATE TABLE IF NOT EXISTS "amuxc_path_acl" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"team_id" uuid NOT NULL,
	"path_prefix" text NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "amuxc_path_acl_prefix_uniq" UNIQUE("team_id","path_prefix"),
	CONSTRAINT "amuxc_path_acl_prefix_shape" CHECK ("path_prefix" LIKE 'knowledge/%' AND "path_prefix" LIKE '%/')
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "amuxc_path_acl" ADD CONSTRAINT "amuxc_path_acl_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "amuxc_path_acl" ADD CONSTRAINT "amuxc_path_acl_created_by_actors_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."actors"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_amuxc_path_acl_team" ON "amuxc_path_acl" USING btree ("team_id");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "amuxc_path_acl_grants" (
	"acl_id" uuid NOT NULL,
	"actor_id" uuid NOT NULL,
	"permissions" varchar(32) DEFAULT 'a:m:d' NOT NULL,
	"granted_by" uuid NOT NULL,
	"granted_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "amuxc_path_acl_grants_acl_id_actor_id_pk" PRIMARY KEY("acl_id","actor_id")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "amuxc_path_acl_grants" ADD CONSTRAINT "amuxc_path_acl_grants_acl_id_fk" FOREIGN KEY ("acl_id") REFERENCES "public"."amuxc_path_acl"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "amuxc_path_acl_grants" ADD CONSTRAINT "amuxc_path_acl_grants_actor_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."actors"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "amuxc_path_acl_grants" ADD CONSTRAINT "amuxc_path_acl_grants_granted_by_fk" FOREIGN KEY ("granted_by") REFERENCES "public"."actors"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_amuxc_path_acl_grants_actor" ON "amuxc_path_acl_grants" USING btree ("actor_id");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "amuxc_access_log" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"team_id" uuid NOT NULL,
	"actor_id" uuid NOT NULL,
	"path_prefix" text NOT NULL,
	"path" text,
	"action" text NOT NULL,
	"allowed" boolean NOT NULL,
	"at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "amuxc_access_log_action_check" CHECK ("action" IN ('manifest','download','upload','delete','versions'))
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "amuxc_access_log" ADD CONSTRAINT "amuxc_access_log_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "amuxc_access_log" ADD CONSTRAINT "amuxc_access_log_actor_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."actors"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_amuxc_access_log_team_at" ON "amuxc_access_log" USING btree ("team_id","at" DESC);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_amuxc_access_log_prefix" ON "amuxc_access_log" USING btree ("team_id","path_prefix","at" DESC);
