#!/usr/bin/env bash
#
# Build the CJK subset font used by the face screens.
#
# The device renders a small, fixed set of Chinese strings (idle quips, state
# labels, error lines, seeded notes). A full CJK face is several MB; this subset
# is a few KB.
#
# The glyph set is EXTRACTED FROM THE SOURCE, not maintained by hand — a
# hand-kept list silently drifts the moment someone adds a string, and the
# symptom is a single tofu box on a device you cannot easily inspect.
#
# Dynamic note text (milestone 3, once STT exists) is arbitrary Chinese and
# cannot be subset ahead of time. That needs a full binfont on the storage
# partition via lv_binfont_create — see README "Fonts".
#
# Requires node (for npx lv_font_conv).
#
set -euo pipefail

cd "$(dirname "$0")/.."

OUT_DIR="main/assets/fonts"
SIZES=(18 22)

# --- font source -------------------------------------------------------------
# Prefer an explicitly supplied face; otherwise use the Source Han Sans SC that
# LVGL already ships for its own CJK built-ins (SIL OFL). Using it avoids an
# external download entirely.
CANDIDATES=(
  "tools/fonts/NotoSansSC-Medium.ttf"
  "components/lvgl/scripts/built_in_font/SourceHanSansSC-Normal.otf"
)
FONT=""
for c in "${CANDIDATES[@]}"; do
  if [[ -f "$c" ]]; then FONT="$c"; break; fi
done
if [[ -z "$FONT" ]]; then
  echo "error: no CJK font found. Tried:" >&2
  printf '  %s\n' "${CANDIDATES[@]}" >&2
  echo >&2
  echo "Run ./fetch_repos.py (LVGL bundles Source Han Sans SC), or drop a TTF at" >&2
  echo "tools/fonts/NotoSansSC-Medium.ttf" >&2
  exit 1
fi
echo "font source: $FONT"

if ! command -v node >/dev/null 2>&1; then
  echo "error: node not found (brew install node)" >&2
  exit 1
fi

# --- glyph set ---------------------------------------------------------------
# Every non-ASCII character appearing in a string literal anywhere in our own
# sources. Deliberately over-inclusive: a stray extra glyph costs bytes, a
# missing one costs a tofu box.
SYMBOLS=$(node -e '
const fs = require("fs"), path = require("path");
const roots = ["main/face", "main/main.cpp", "main/power"];
const files = [];
const walk = p => {
  if (!fs.existsSync(p)) return;
  const st = fs.statSync(p);
  if (st.isDirectory()) fs.readdirSync(p).forEach(f => walk(path.join(p, f)));
  else if (/\.(c|cc|cpp|h|hpp)$/.test(p)) files.push(p);
};
roots.forEach(walk);
const set = new Set();
for (const f of files) {
  for (const ch of fs.readFileSync(f, "utf8")) {
    const cp = ch.codePointAt(0);
    // Anything outside ASCII that is not a control char or whitespace.
    if (cp > 0x7f && !/\s/.test(ch)) set.add(ch);
  }
}
process.stdout.write([...set].sort().join(""));
')

if [[ -z "$SYMBOLS" ]]; then
  echo "error: extracted no non-ASCII glyphs — did the source move?" >&2
  exit 1
fi
echo "glyphs: ${#SYMBOLS} distinct"

mkdir -p "$OUT_DIR"

for size in "${SIZES[@]}"; do
  npx --yes lv_font_conv \
    --font "$FONT" \
    --size "$size" \
    --bpp 4 \
    --format lvgl \
    --lv-include lvgl.h \
    --symbols "$SYMBOLS" \
    --range 0x20-0x7F \
    --no-compress \
    -o "$OUT_DIR/face_font_cjk_${size}.c"
  echo "wrote $OUT_DIR/face_font_cjk_${size}.c"
done

cat > "$OUT_DIR/face_font_cjk.h" <<'HDR'
/* Generated by tools/gen_fonts.sh — do not edit. */
#pragma once
#include <lvgl.h>

/* The generated tables compile as C, so their symbols are unmangled. Without
 * this guard a C++ translation unit declares them with C++ linkage and the
 * build fails at link time with an undefined reference. */
#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(face_font_cjk_18);
LV_FONT_DECLARE(face_font_cjk_22);

#ifdef __cplusplus
}
#endif
HDR

echo "wrote $OUT_DIR/face_font_cjk.h"

# Two build-system facts make this necessary, and both fail SILENTLY —
# the build succeeds and the device just renders tofu:
#
#  1. face_ui.cpp picks the font up via `__has_include`. When that header is
#     ABSENT the compiler records no dependency edge on it, so creating it
#     later gives the build system no reason to recompile — the stale object
#     keeps the Montserrat fallback it was built with.
#  2. main/CMakeLists.txt globs sources at CMake *configure* time, so the newly
#     generated .c files are not in the build until CMake re-runs.
touch main/face/face_ui.cpp
touch main/CMakeLists.txt
echo "touched face_ui.cpp + CMakeLists.txt (see comment in this script for why)"
echo
echo "Now: idf.py build"
