/* Generated by tools/gen_fonts.sh — do not edit. */
#pragma once
#include <lvgl.h>

/* The generated tables compile as C, so their symbols are unmangled. Without
 * this guard a C++ translation unit declares them with C++ linkage and the
 * build fails at link time with an undefined reference. */
#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(face_font_cjk_18);
LV_FONT_DECLARE(face_font_cjk_22);

#ifdef __cplusplus
}
#endif
