import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Parts of `lib/` are compiled by other packages, and none of them resolve the
 * `@/` alias — it is defined only in this package's `tsconfig.json` and
 * `vite.config.ts`. A `@/` import in a shared file therefore resolves here and
 * fails there, in *that* package's build, which this suite never runs.
 *
 * The two ways a file becomes shared, both read from source below rather than
 * listed by hand — a hand-written list is what let `lib/proto` through:
 *
 *   1. `packages/app/package.json` `exports` publishes it to the workspace
 *      (`apps/expo` imports `@teamclu/app/proto/*` this way).
 *   2. `apps/extension/tsconfig.json` aliases it as `@teamclu/*`
 *      (link-hover, link-session).
 *
 * Reachability is transitive: a shared entry point drags in whatever it
 * imports relatively, so the scan follows those edges.
 */
const HERE = path.dirname(fileURLToPath(import.meta.url));
const APP = path.resolve(HERE, '..', '..', '..');          // packages/app
const SRC = path.join(APP, 'src');
const REPO = path.resolve(APP, '..', '..');

/** Entry points other packages compile, from the two sources above. */
function sharedEntryPoints(): string[] {
  const out: string[] = [];

  const pkg = JSON.parse(fs.readFileSync(path.join(APP, 'package.json'), 'utf8'));
  for (const target of Object.values(pkg.exports ?? {}) as string[]) {
    out.push(path.resolve(APP, target));
  }

  const extTsconfig = path.join(REPO, 'apps', 'extension', 'tsconfig.json');
  if (fs.existsSync(extTsconfig)) {
    // Strip comments — the file is JSONC.
    const raw = fs.readFileSync(extTsconfig, 'utf8').replace(/^\s*\/\/.*$/gm, '');
    for (const [, target] of raw.matchAll(/"@teamclu\/[^"]*":\s*\[\s*"([^"]+)"/g)) {
      const resolved = path.resolve(path.dirname(extTsconfig), target.replace(/\/\*$/, ''));
      out.push(resolved);
    }
  }
  return out;
}

function resolveModule(spec: string, fromDir: string): string | null {
  const base = path.resolve(fromDir, spec);
  for (const candidate of [base, `${base}.ts`, `${base}.tsx`,
                           path.join(base, 'index.ts'), path.join(base, 'index.tsx')]) {
    if (fs.existsSync(candidate) && fs.statSync(candidate).isFile()) return candidate;
  }
  return null;
}

/** Every file reachable from a shared entry point by relative import. */
function sharedFiles(): Set<string> {
  const seen = new Set<string>();
  const queue: string[] = [];

  for (const entry of sharedEntryPoints()) {
    if (fs.existsSync(entry) && fs.statSync(entry).isDirectory()) {
      for (const name of fs.readdirSync(entry)) {
        if (/\.tsx?$/.test(name)) queue.push(path.join(entry, name));
      }
    } else {
      const file = resolveModule(entry, path.dirname(entry));
      if (file) queue.push(file);
    }
  }

  while (queue.length) {
    const file = queue.pop()!;
    if (seen.has(file) || !file.startsWith(SRC)) continue;
    seen.add(file);
    const text = fs.readFileSync(file, 'utf8');
    for (const [, spec] of text.matchAll(/['"](\.{1,2}\/[^'"]+)['"]/g)) {
      const next = resolveModule(spec, path.dirname(file));
      if (next) queue.push(next);
    }
  }
  return seen;
}

describe('lib files that other packages compile', () => {
  it('never use the @/ alias, which only this package resolves', () => {
    const offenders: string[] = [];
    for (const file of sharedFiles()) {
      const text = fs.readFileSync(file, 'utf8');
      for (const [, spec] of text.matchAll(/['"](@\/[^'"]+)['"]/g)) {
        offenders.push(`${path.relative(SRC, file)}: ${spec}`);
      }
    }
    // If this fails, use a relative import there. `lib/proto/teamclu_pb.ts` is
    // also generated by `pnpm proto-gen`, so an alias in it does not survive
    // regeneration either.
    expect(offenders.sort()).toEqual([]);
  });

  it('found the entry points it is supposed to guard', () => {
    const files = [...sharedFiles()].map((f) => path.relative(SRC, f));
    // The published proto surface (apps/expo) and the extension-shared dirs.
    expect(files).toContain(path.join('lib', 'proto', 'teamclu_pb.ts'));
    expect(files).toContain(path.join('lib', 'proto', 'amux_pb.ts'));
    expect(files.some((f) => f.includes(path.join('extension', 'link-hover')))).toBe(true);
    expect(files.some((f) => f.includes(path.join('extension', 'link-session')))).toBe(true);
  });
});
